export const standStraight = {
  humanRotation: 0,
  headRotation: 0,
  foreUpperArmRotation: 180,
  foreLowerArmRotation: 0,
  foreHandRotation: 0,
  hindUpperArmRotation: 180,
  hindLowerArmRotation: 0,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -20,
  foreLowerLegRotation: 0,
  foreFootRotation: 70,
  hindUpperLegRotation: -20,
  hindLowerLegRotation: 0,
  hindFootRotation: 70,
  offsetX: 0,
  offsetY: 0,
  
  borderX0: -30,
  borderX1: 30,
  borderY0: -120,
  borderY1: 180,
};

export const standCasual = {
  humanRotation: 358,
  headRotation: 0,
  foreUpperArmRotation: 174,
  foreLowerArmRotation: 13,
  foreHandRotation: 0,
  hindUpperArmRotation: 181,
  hindLowerArmRotation: 15,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -4,
  foreLowerLegRotation: -15,
  foreFootRotation: 70,
  hindUpperLegRotation: -19,
  hindLowerLegRotation: -10,
  hindFootRotation: 83,

  offsetX: 0,
  offsetY: 0,
  borderX0: -45,
  borderX1: 20,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride1 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 184,
  foreLowerArmRotation: 24,
  foreHandRotation: 8,
  hindUpperArmRotation: 174,
  hindLowerArmRotation: 27,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -3,
  foreLowerLegRotation: -19,
  foreFootRotation: 69,
  hindUpperLegRotation: 30,
  hindLowerLegRotation: -87,
  hindFootRotation: 66,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride2 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 204,
  foreLowerArmRotation: 24,
  foreHandRotation: 8,
  hindUpperArmRotation: 142,
  hindLowerArmRotation: 24,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -26,
  foreLowerLegRotation: -1,
  foreFootRotation: 76,
  hindUpperLegRotation: 45,
  hindLowerLegRotation: -71,
  hindFootRotation: 57,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride3 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 204,
  foreLowerArmRotation: 38,
  foreHandRotation: 8,
  hindUpperArmRotation: 150,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -26,
  foreLowerLegRotation: -48,
  foreFootRotation: 74,
  hindUpperLegRotation: 18,
  hindLowerLegRotation: -13,
  hindFootRotation: 67,

  offsetX: 0,
  offsetY: 10,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride4 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 173,
  foreLowerArmRotation: 38,
  foreHandRotation: 8,
  hindUpperArmRotation: 160,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 6,
  foreLowerLegRotation: -62,
  foreFootRotation: 56,
  hindUpperLegRotation: -5,
  hindLowerLegRotation: -15,
  hindFootRotation: 74,

  offsetX: 0,
  offsetY: 2,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride5 = {
  humanRotation: 353,
  headRotation: 2,
  foreUpperArmRotation: 154,
  foreLowerArmRotation: 38,
  foreHandRotation: 6,
  hindUpperArmRotation: 180,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 40,
  foreLowerLegRotation: -62,
  foreFootRotation: 80,
  hindUpperLegRotation: -31,
  hindLowerLegRotation: -13,
  hindFootRotation: 90,

  offsetX: 0,
  offsetY: 5,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const walkStride6 = {
  humanRotation: 354,
  headRotation: 2,
  foreUpperArmRotation: 144,
  foreLowerArmRotation: 38,
  foreHandRotation: 6,
  hindUpperArmRotation: 190,
  hindLowerArmRotation: 34,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 20,
  foreLowerLegRotation: -21,
  foreFootRotation: 80,
  hindUpperLegRotation: -40,
  hindLowerLegRotation: -20,
  hindFootRotation: 70,

  offsetX: 0,
  offsetY: 10,
  borderX0: -100,
  borderX1: 80,
  borderY0: -120,
  borderY1: 180,
};

export const runStride1 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 139,
  foreLowerArmRotation: 81,
  foreHandRotation: 0,
  hindUpperArmRotation: 195,
  hindLowerArmRotation: 85,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 35,
  foreLowerLegRotation: -68,
  foreFootRotation: 87,
  hindUpperLegRotation: -30,
  hindLowerLegRotation: -73,
  hindFootRotation: 80,

  offsetX: 0,
  offsetY: 20,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const runStride2 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 204,
  foreLowerArmRotation: 81,
  foreHandRotation: 0,
  hindUpperArmRotation: 113,
  hindLowerArmRotation: 85,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -3,
  foreLowerLegRotation: -33,
  foreFootRotation: 80,
  hindUpperLegRotation: 56,
  hindLowerLegRotation: -110,
  hindFootRotation: 80,

  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const runStride3 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 239,
  foreLowerArmRotation: 110,
  foreHandRotation: 0,
  hindUpperArmRotation: 121,
  hindLowerArmRotation: 45,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -25,
  foreLowerLegRotation: -60,
  foreFootRotation: 70,
  hindUpperLegRotation: 69,
  hindLowerLegRotation: -90,
  hindFootRotation: 81,

  offsetX: 0,
  offsetY: 5,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const runStride4 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 195,
  foreLowerArmRotation: 85,
  foreHandRotation: 0,
  hindUpperArmRotation: 139,
  hindLowerArmRotation: 81,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -30,
  foreLowerLegRotation: -73,
  foreFootRotation: 80,
  hindUpperLegRotation: 35,
  hindLowerLegRotation: -68,
  hindFootRotation: 87,

  offsetX: 0,
  offsetY: 10,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const runStride5 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 113,
  foreLowerArmRotation: 85,
  foreHandRotation: 0,
  hindUpperArmRotation: 204,
  hindLowerArmRotation: 81,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 56,
  foreLowerLegRotation: -110,
  foreFootRotation: 80,
  hindUpperLegRotation: -3,
  hindLowerLegRotation: -33,
  hindFootRotation: 80,

  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const runStride6 = {
  humanRotation: 341,
  headRotation: -2,
  foreUpperArmRotation: 121,
  foreLowerArmRotation: 45,
  foreHandRotation: 0,
  hindUpperArmRotation: 239,
  hindLowerArmRotation: 110,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 69,
  foreLowerLegRotation: -90,
  foreFootRotation: 81,
  hindUpperLegRotation: -25,
  hindLowerLegRotation: -60,
  hindFootRotation: 70,

  offsetX: 0,
  offsetY: 5,
  borderX0: -120,
  borderX1: 120,
  borderY0: -120,
  borderY1: 180,
};

export const jumpPrime = {
  humanRotation: 340,
  headRotation: 5,
  foreUpperArmRotation: 145,
  foreLowerArmRotation: 100,
  foreHandRotation: 0,
  hindUpperArmRotation: 160,
  hindLowerArmRotation: 100,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 53,
  foreLowerLegRotation: -105,
  foreFootRotation: 88,
  hindUpperLegRotation: -14,
  hindLowerLegRotation: -65,
  hindFootRotation: 89,
  offsetX: 0,
  offsetY: 25,
  borderX0: -120,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180
};

export const jumpFly = {
  humanRotation: 350,
  headRotation: 5,
  foreUpperArmRotation: 145,
  foreLowerArmRotation: 48,
  foreHandRotation: 0,
  hindUpperArmRotation: 160,
  hindLowerArmRotation: 56,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: -31,
  foreLowerLegRotation: -33,
  foreFootRotation: 32,
  hindUpperLegRotation: 58,
  hindLowerLegRotation: -106,
  hindFootRotation: 65,
  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180
};

export const jumpPeak = {
  humanRotation: 0,
  headRotation: 5,
  foreUpperArmRotation: 195,
  foreLowerArmRotation: 60,
  foreHandRotation: 0,
  hindUpperArmRotation: 181,
  hindLowerArmRotation: 56,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 11,
  foreLowerLegRotation: -79,
  foreFootRotation: 59,
  hindUpperLegRotation: 68,
  hindLowerLegRotation: -106,
  hindFootRotation: 68,
  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180
};

export const jumpFall = {
  humanRotation: 10,
  headRotation: 5,
  foreUpperArmRotation: 262,
  foreLowerArmRotation: 60,
  foreHandRotation: 0,
  hindUpperArmRotation: 221,
  hindLowerArmRotation: 58,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 70,
  foreLowerLegRotation: -127,
  foreFootRotation: 83,
  hindUpperLegRotation: 18,
  hindLowerLegRotation: -15,
  hindFootRotation: 37,
  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180
};

export const jumpLand = {
  humanRotation: 5,
  headRotation: 5,
  foreUpperArmRotation: 173,
  foreLowerArmRotation: 80,
  foreHandRotation: 0,
  hindUpperArmRotation: 150,
  hindLowerArmRotation: 80,
  hindHandRotation: 0,
  hipRotation: 200,
  foreUpperLegRotation: 5,
  foreLowerLegRotation: -94,
  foreFootRotation: 83,
  hindUpperLegRotation: 26,
  hindLowerLegRotation: -65,
  hindFootRotation: 73,
  offsetX: 0,
  offsetY: 0,
  borderX0: -120,
  borderX1: 100,
  borderY0: -120,
  borderY1: 180
};

export const standJumpPrime = {
  humanRotation: 341,
  headRotation: 4,
  foreUpperArmRotation: 147,
  foreLowerArmRotation: 91,
  foreHandRotation: 0,
  hindUpperArmRotation: 184,
  hindLowerArmRotation: 72,
  hindHandRotation: 0,
  hipRotation: 220,
  foreUpperLegRotation: 58,
  foreLowerLegRotation: -103,
  foreFootRotation: 83,
  hindUpperLegRotation: 25,
  hindLowerLegRotation: -125,
  hindFootRotation: 90,
  offsetX: 0,
  offsetY: 20,
  borderX0: -85,
  borderX1: 45,
  borderY0: -140,
  borderY1: 180
};

export const standJumpFly = {
  humanRotation: 351,
  headRotation: 4,
  foreUpperArmRotation: 165,
  foreLowerArmRotation: 44,
  foreHandRotation: 0,
  hindUpperArmRotation: 160,
  hindLowerArmRotation: 44,
  hindHandRotation: 0,
  hipRotation: 212,
  foreUpperLegRotation: -1,
  foreLowerLegRotation: -55,
  foreFootRotation: 51,
  hindUpperLegRotation: -20,
  hindLowerLegRotation: -40,
  hindFootRotation: 45,
  offsetX: 0,
  offsetY: -20,
  borderX0: -85,
  borderX1: 45,
  borderY0: -140,
  borderY1: 180
};
