const EMOJI_WORDS = [
  {word: "absence", hint: "🚪🌫️"},
  {word: "arrival", hint: "🛣️📍"},
  {word: "balance", hint: "⚖️🌗"},
  {word: "beneath", hint: "⬇️🌑"},
  {word: "between", hint: "↔️🌫️"},
  {word: "binding", hint: "🧵🔗"},
  {word: "clarity", hint: "💡🔍"},
  {word: "closure", hint: "🚪🔒"},
  {word: "collapse", hint: "🏗️⬇️"},
  {word: "collect", hint: "🧲📦"},
  {word: "comfort", hint: "🛏️🌙"},
  {word: "consume", hint: "🔥⬇️"},
  {word: "contour", hint: "🗺️〰️"},
  {word: "converge", hint: "↘️↙️"},
  {word: "current", hint: "🌊➡️"},
  {word: "decline", hint: "📉🌒"},
  {word: "deliver", hint: "📦➡️"},
  {word: "density", hint: "🧱📦"},
  {word: "descend", hint: "⬇️🌫️"},
  {word: "despair", hint: "🌑💧"},
  {word: "destiny", hint: "🧭✨"},
  {word: "detour", hint: "↩️🛣️"},
  {word: "devour", hint: "🔥🍽️"},
  {word: "distant", hint: "🌄🌫️"},
  {word: "drifting", hint: "🍃➡️"},
  {word: "drought", hint: "☀️🚫💧"},
  {word: "echoing", hint: "🔊↩️"},
  {word: "eclipse", hint: "🌑☀️"},
  {word: "endless", hint: "🔁🌌"},
  {word: "engrave", hint: "🪨✍️"},
  {word: "entwine", hint: "🧵🌀"},
  {word: "erosion", hint: "🌊🪨"},
  {word: "essence", hint: "✨🫧"},
  {word: "eternal", hint: "♾️🌌"},
  {word: "evident", hint: "🔍💡"},
  {word: "exhaust", hint: "🔋⬇️"},
  {word: "faction", hint: "👥↔️"},
  {word: "falter", hint: "⏸️➡️"},
  {word: "fervent", hint: "🔥❤️"},
  {word: "flicker", hint: "🕯️〰️"},
  {word: "fracture", hint: "🪨⚡"},
  {word: "fraying", hint: "🧵⬇️"},
  {word: "freight", hint: "📦🚚"},
  {word: "furnace", hint: "🔥🏭"},
  {word: "glacier", hint: "❄️➡️"},
  {word: "glimmer", hint: "✨🌫️"},
  {word: "gravity", hint: "⬇️🌍"},
  {word: "harbour", hint: "⚓🌊"},
  {word: "horizon", hint: "🌄↔️"},
  {word: "humbled", hint: "⬇️🧍"},
  {word: "immerse", hint: "🌊⬇️"},
  {word: "inertia", hint: "🪨⏸️"},
  {word: "journey", hint: "🛣️⏳"},
  {word: "lantern", hint: "🏮🌫️"},
  {word: "lattice", hint: "🔲🕸️"},
  {word: "lingers", hint: "⏳🌫️"},
  {word: "lowland", hint: "⬇️🌧️"},
  {word: "meander", hint: "〰️➡️"},
  {word: "meridian", hint: "🌍📏"},
  {word: "midnight", hint: "🌙🕛"},
  {word: "miracle", hint: "✨❓"},
  {word: "monolith", hint: "🪨⬆️"},
  {word: "murmurs", hint: "🔊🌫️"},
  {word: "network", hint: "🕸️🔗"},
  {word: "nomadic", hint: "🛣️🏕️"},
  {word: "notion", hint: "💭❓"},
  {word: "obelisk", hint: "🪨⬆️"},
  {word: "obscure", hint: "🌫️❓"},
  {word: "outlast", hint: "⏳🏁"},
  {word: "overcast", hint: "☁️🌫️"},
  {word: "passage", hint: "🚪➡️"},
  {word: "patience", hint: "⏳🧘"},
  {word: "pendant", hint: "🔗❤️"},
  {word: "perilous", hint: "⚠️🌫️"},
  {word: "persist", hint: "➡️⏳"},
  {word: "plateau", hint: "⬆️⏸️"},
  {word: "plummet", hint: "⬇️⚡"},
  {word: "precise", hint: "🎯📏"},
  {word: "quarrel", hint: "🗣️⚡"},
  {word: "radiant", hint: "✨☀️"},
  {word: "ravaged", hint: "🔥🪨"},
  {word: "reckless", hint: "⚡➡️"},
  {word: "remnant", hint: "🧩⬇️"},
  {word: "resolve", hint: "🧠✔️"},
  {word: "retreat", hint: "⬅️🏃"},
  {word: "reverie", hint: "💭🌙"},
  {word: "rupture", hint: "⚡🪨"},
  {word: "scarred", hint: "🪨〰️"},
  {word: "seeking", hint: "🔍➡️"},
  {word: "serpent", hint: "〰️🐍"},
  {word: "shadowed", hint: "🌑➡️"},
  {word: "shatter", hint: "💥🪨"},
  {word: "silence", hint: "🔇🌫️"},
  {word: "solitary", hint: "🧍🌌"},
  {word: "spectrum", hint: "🌈📏"},
  {word: "spiraling", hint: "🌀⬇️"},
  {word: "stagnant", hint: "⏸️🌊"},
  {word: "starlit", hint: "✨🌌"},
  {word: "subtlety", hint: "🌫️🔍"},
  {word: "surging", hint: "🌊⚡"},
  {word: "terrain", hint: "🗺️🪨"},
  {word: "torrent", hint: "🌊⬇️"},
  {word: "traverse", hint: "➡️🗺️"},
  {word: "tremble", hint: "〰️🪨"},
  {word: "twilight", hint: "🌗🌫️"},
  {word: "unearth", hint: "⬇️🪨"},
  {word: "unravel", hint: "🧵⬇️"},
  {word: "updraft", hint: "⬆️🌬️"},
  {word: "venture", hint: "➡️❓"},
  {word: "vibrant", hint: "✨🌈"},
  {word: "visible", hint: "👁️💡"},
  {word: "waiting", hint: "⏳🧍"},
  {word: "waypoint", hint: "📍➡️"},
  {word: "weathered", hint: "🌧️🪨"},
  {word: "whisper", hint: "🤫🌬️"},
  {word: "withstand", hint: "🪨⚡"},
  {word: "yearning", hint: "❤️➡️"}
];

const DEFINED_WORDS = [
  {word: "janzen", hint: "The name of an engineer/programmer/researcher that you should hire"},
  {word: "bridge", hint: "It brings two sides together without belonging to either"},
  {word: "candle", hint: "Darkness retreats from its company"},
  {word: "forest", hint: "A city that grew without architects"},
  {word: "mirror", hint: "It only tells the truth about other people"},
  {word: "anchor", hint: "Keeps things from drifting"},
  {word: "marble", hint: "Cold, smooth, and worth a competition"},
  {word: "ladder", hint: "Ambition often takes this form"},
  {word: "castle", hint: "Built for kings who feared their neighbours"},
  {word: "garden", hint: "Patience rewarded in seasons"},
  {word: "hunter", hint: "Always moving toward something that runs"},
  {word: "riddle", hint: "The answer was there before the question"},
  {word: "flicker", hint: "Not quite committed to staying lit"},
  {word: "cinder", hint: "What fire leaves behind as a souvenir"},
  {word: "murmur", hint: "A sound that refuses to commit to words"},
  {word: "cobweb", hint: "An abandoned building project"},
  {word: "burrow", hint: "Home is underground for some"},
  {word: "pebble", hint: "A boulder with a long history"},
  {word: "quiver", hint: "Holds what is meant to fly"},
  {word: "shroud", hint: "Covers what others shouldn't see"},
  {word: "fallow", hint: "Resting so it can give more later"},
  {word: "tangle", hint: "Order's undoing"},
  {word: "wither", hint: "What happens to neglected things"},
  {word: "gravel", hint: "Smaller than a stone, louder underfoot"},
  {word: "hollow", hint: "Empty, but shaped by what was once inside"},
  {word: "mellow", hint: "Edges worn smooth by time"},
  {word: "famine", hint: "Too much absence of one necessary thing"},
  {word: "gallop", hint: "Speed that can be heard before it's seen"},
  {word: "magnet", hint: "Pulls without asking permission"},
  {word: "plunge", hint: "Commitment made with the whole body"},
  {word: "ripple", hint: "A small event with wide consequences"},
  {word: "rustle", hint: "Movement announced quietly"},
  {word: "sorrow", hint: "Love with nowhere to go"},
  {word: "frozen", hint: "Caught mid-motion"},
  {word: "refuge", hint: "A place that asks nothing of you"},
  {word: "tremor", hint: "The earth expressing discomfort"},
  {word: "unkempt", hint: "Forgot to keep up appearances"},
  {word: "wander", hint: "No destination required"},
  {word: "window", hint: "Inside looking out, outside looking in"},
  {word: "tundra", hint: "Where the ground never quite thaws"},
  {word: "simmer", hint: "Not quite boiling, but getting there"},
  {word: "rafter", hint: "Holds the ceiling up from above"},
  {word: "mortar", hint: "What keeps the bricks honest"},
  {word: "locket", hint: "Keeps something close to the heart"},
  {word: "grotto", hint: "A cave that someone decided was charming"},
  {word: "fugitive", hint: "Running toward somewhere by running away"},
  {word: "compass", hint: "Knows north without being told"},
  {word: "silence", hint: "The loudest thing in an empty room"},
  {word: "eclipse", hint: "One body steps into another's spotlight"},
  {word: "lantern", hint: "A portable piece of day"},
  {word: "phantom", hint: "Leaves no footprints"},
  {word: "thunder", hint: "Light's slower, louder companion"},
  {word: "pilgrim", hint: "The journey is the whole point"},
  {word: "granite", hint: "Patience measured in millennia"},
  {word: "curtain", hint: "Marks where the private world begins"},
  {word: "tempest", hint: "Shakespeare named a play after it"},
  {word: "blanket", hint: "Comfort made tangible"},
  {word: "starlight", hint: "Older than you might think"},
  {word: "sandstorm", hint: "The desert rearranging itself"},
  {word: "labyrinth", hint: "The way out and the way in look the same"},
  {word: "clockwork", hint: "Everything on time, nothing by chance"},
  {word: "telescope", hint: "Makes the distant feel closer than it is"},
  {word: "shipwreck", hint: "A voyage that ran out of luck"},
  {word: "blueprint", hint: "The building before the building"},
  {word: "threshold", hint: "Neither here nor there"},
  {word: "cathedral", hint: "Stone arranged to inspire vertigo"},
  {word: "solitude", hint: "Chosen aloneness"},
  {word: "abstract", hint: "Resists being held in one hand"},
  {word: "dormant", hint: "Waiting without admitting it"},
  {word: "drought", hint: "A sky that keeps its promises"},
  {word: "ferment", hint: "Transformation through patient chaos"},
  {word: "glacier", hint: "Rivers that forgot how to hurry"},
  {word: "gravity", hint: "The universe's most reliable habit"},
  {word: "harvest", hint: "The reward end of a long conversation with the soil"},
  {word: "horizon", hint: "Always the same distance away"},
  {word: "isthmus", hint: "The thin part holding two larger things together"},
  {word: "landfill", hint: "Where things go when we stop wanting them"},
  {word: "mirage", hint: "Proof that heat distorts desire"},
  {word: "monsoon", hint: "A season defined by what falls from the sky"},
  {word: "nomadic", hint: "Home is wherever you stopped last"},
  {word: "orchard", hint: "A field that learned patience"},
  {word: "passage", hint: "Connects two places without being either"},
  {word: "plateau", hint: "Got high and then stopped"},
  {word: "quarry", hint: "What's left after taking the useful parts"},
  {word: "ravine", hint: "A valley with stronger opinions"},
  {word: "remnant", hint: "What survives when the rest is gone"},
  {word: "residue", hint: "Evidence of what was"},
  {word: "solstice", hint: "The sun at its most committed"},
  {word: "summit", hint: "Hard to reach, easy to leave"},
  {word: "thicket", hint: "A forest too busy to be entered politely"},
  {word: "twilight", hint: "The sky can't decide"},
  {word: "undone", hint: "Progress reversed"},
  {word: "uproot", hint: "Torn from where it belonged"},
  {word: "vantage", hint: "Height used for perspective"},
  {word: "vestige", hint: "A trace that outlasted the thing itself"},
  {word: "vintage", hint: "Better for having waited"},
  {word: "vortex", hint: "Everything spirals toward the middle"},
  {word: "wayfarer", hint: "Someone who walks as a way of thinking"},
  {word: "wreckage", hint: "The aftermath of momentum"},
  {word: "zephyr", hint: "Wind that doesn't mean any harm"},
  {word: "torrent", hint: "Water with an agenda"},
  {word: "forsaken", hint: "Left behind deliberately"},
  {word: "shiver", hint: "The body expressing what words can't"},
  {word: "smolder", hint: "Fire being modest about itself"},
  {word: "fracture", hint: "Where something was whole"},
  {word: "drifting", hint: "Movement with no vote on the direction"},
  {word: "barren", hint: "Rich in absence"},
  {word: "obscure", hint: "Exists but resists being found"},
  {word: "unravel", hint: "Order giving way thread by thread"},
  {word: "descent", hint: "The easier half of the mountain"},
  {word: "ancient", hint: "Older than anyone alive can remember"},
  {word: "cavern", hint: "A room the earth made for itself"},
  {word: "crevice", hint: "Too small to be a gap, too useful to ignore"},
  {word: "cypress", hint: "A tree that points at the sky"},
  {word: "desolate", hint: "Emptiness that used to be fullness"},
  {word: "embers", hint: "Fire's quieter afterthought"},
  {word: "eternal", hint: "Refuses the concept of endings"},
  {word: "exhaust", hint: "What remains after everything is spent"},
  {word: "fissure", hint: "The crack before the break"},
  {word: "floodgate", hint: "One thing holding everything back"},
  {word: "forsook", hint: "Past tense of abandonment"},
  {word: "galleon", hint: "A ship built for distance and wealth"},
  {word: "gargoyle", hint: "Ugliness put to architectural use"},
  {word: "glimmer", hint: "Light not quite committing to presence"},
  {word: "gnarled", hint: "Shaped by years of resistance"},
  {word: "granite", hint: "What mountains are made of, mostly"},
  {word: "grizzled", hint: "Experience written on the face"},
  {word: "haggard", hint: "The look of a long ordeal"},
  {word: "hermit", hint: "Chose the absence of others"},
  {word: "hoarfrost", hint: "Winter's overnight decoration"},
  {word: "heirloom", hint: "An object weighted with history"},
  {word: "howling", hint: "The wind making its feelings known"},
  {word: "iceberg", hint: "Mostly private"},
  {word: "kindling", hint: "Ready to become something else"},
  {word: "laborer", hint: "Work measured in hours and muscle"},
  {word: "lattice", hint: "A pattern of deliberate gaps"},
  {word: "lineage", hint: "The long chain of people you came from"},
  {word: "linger", hint: "Refuses to leave on time"},
  {word: "lowland", hint: "Where the water ends up"},
  {word: "lurking", hint: "Present but unannounced"},
  {word: "mariner", hint: "Someone whose road is water"},
  {word: "marshland", hint: "Couldn't decide between land and water"},
  {word: "masonry", hint: "The art of stacking things that last"},
  {word: "meadow", hint: "A field that kept its wildness"},
  {word: "meridian", hint: "An imaginary line the world agreed on"},
  {word: "migrate", hint: "Follows something warmer"},
  {word: "mineral", hint: "What the earth is mostly made of"},
  {word: "minstrel", hint: "Carried news before newspapers existed"},
  {word: "moraine", hint: "A glacier's leftover pile"},
  {word: "mottled", hint: "Colour arrived unevenly"},
  {word: "mournful", hint: "Weighted by something lost"},
  {word: "mudflat", hint: "Where rivers slow down and think"},
  {word: "muskrat", hint: "Lives between the water and the land"},
  {word: "mystery", hint: "Knows something you don't"},
  {word: "neglect", hint: "Harm done by not doing"},
  {word: "network", hint: "Strength borrowed from connection"},
  {word: "nightfall", hint: "The day handing over to its opposite"},
  {word: "oblique", hint: "Won't come at it directly"},
  {word: "outcast", hint: "Pushed to the edges by the centre"},
  {word: "outpost", hint: "Far from home but serving it"},
  {word: "overgrown", hint: "Nature reclaiming its territory"},
  {word: "parapet", hint: "The wall that lets you look without falling"},
  {word: "pathways", hint: "Made by repeated choosing"},
  {word: "patchwork", hint: "Unity made from mismatched parts"},
  {word: "penance", hint: "What guilt demands of the body"},
  {word: "peregrine", hint: "A traveller, or the fastest thing alive"},
  {word: "persist", hint: "Continuing past the point of welcome"},
  {word: "phantom", hint: "Exists in some senses but not all"},
  {word: "pinnacle", hint: "As high as this particular thing goes"},
  {word: "pioneer", hint: "First to go where others hadn't"},
  {word: "plunder", hint: "Taking what wasn't offered"},
  {word: "ponder", hint: "Thinking slowly on purpose"},
  {word: "portent", hint: "What happens before something larger"},
  {word: "prowling", hint: "Moving with intent not yet declared"},
  {word: "quarrel", hint: "Two people sharing one problem loudly"},
  {word: "quagmire", hint: "The more you struggle the worse it gets"},
  {word: "quicksand", hint: "Stable until it isn't"},
  {word: "radiant", hint: "Light that comes from within"},
  {word: "rainforest", hint: "Somewhere the sky falls constantly"},
  {word: "rampart", hint: "A wall built with enemies in mind"},
  {word: "reckless", hint: "Speed and confidence without caution"},
  {word: "reckon", hint: "What happens before you decide"},
  {word: "refuge", hint: "A place that holds you without asking why"},
  {word: "relentless", hint: "Doesn't know how to stop"},
  {word: "remnants", hint: "What the fire left alone"},
  {word: "renown", hint: "Known further than you've travelled"},
  {word: "resilient", hint: "Bends but returns"},
  {word: "restless", hint: "Can't stay where it is"},
  {word: "ridgeline", hint: "The mountain's sharp signature"},
  {word: "riftzone", hint: "Where the ground disagrees with itself"},
  {word: "rugged", hint: "Not built for comfort, built for lasting"},
  {word: "rumbling", hint: "A warning arriving from below"},
  {word: "saltwater", hint: "What covers most of the world"},
  {word: "scaffold", hint: "Helps build what will outlast it"},
  {word: "scarcity", hint: "Value born from not enough"},
  {word: "scorched", hint: "Heat's signature on a surface"},
  {word: "seamless", hint: "No visible joints"},
  {word: "sentinel", hint: "Watches so others don't have to"},
  {word: "serpent", hint: "Movement without limbs"},
  {word: "shallow", hint: "Doesn't go very far down"},
  {word: "shrivel", hint: "Drying into a smaller version"},
  {word: "silence", hint: "What fills a room when no one speaks"},
  {word: "silhouette", hint: "The shape without the detail"},
  {word: "sinister", hint: "Something isn't right here"},
  {word: "solstice", hint: "When the sun peaks and turns back"},
  {word: "spartan", hint: "Less by design, not accident"},
  {word: "splinter", hint: "Part of something that became sharp"},
  {word: "stalwart", hint: "Doesn't move when things get hard"},
  {word: "stampede", hint: "Fear made collective and loud"},
  {word: "starving", hint: "Need made urgent"},
  {word: "steadfast", hint: "Didn't move when everything else did"},
  {word: "sterile", hint: "Nothing grows here"},
  {word: "stranded", hint: "Got somewhere without a way back"},
  {word: "submerge", hint: "Goes under entirely"},
  {word: "sunken", hint: "Once higher, now not"},
  {word: "surplus", hint: "More than enough, which creates its own problems"},
  {word: "swelter", hint: "Heat that won't stay outside"},
  {word: "tangled", hint: "In need of patient undoing"},
  {word: "tarnish", hint: "Silver admitting it's been ignored"},
  {word: "tension", hint: "The feeling between a decision and its making"},
  {word: "terrain", hint: "The ground beneath everything"},
  {word: "thicket", hint: "Too dense to walk through politely"},
  {word: "timber", hint: "A tree with a future as something else"},
  {word: "torchlight", hint: "What brave people carry into dark places"},
  {word: "treason", hint: "Betrayal from someone trusted"},
  {word: "trekking", hint: "Walking as a form of commitment"},
  {word: "turmoil", hint: "When the inside matches a storm"},
  {word: "uncharted", hint: "The map ends here"},
  {word: "undermine", hint: "Weakens from beneath"},
  {word: "unfurling", hint: "Opening slowly, like a flag or a fern"},
  {word: "ungainly", hint: "More effective than it looks"},
  {word: "unknown", hint: "Not ignorance, just not yet"},
  {word: "vagrant", hint: "Moves not from wanderlust but from necessity"},
  {word: "valiant", hint: "Brave despite knowing the odds"},
  {word: "vanished", hint: "Was here, now isn't"},
  {word: "verdant", hint: "Green in the richest sense"},
  {word: "vigilant", hint: "Watching for what hasn't happened yet"},
  {word: "visceral", hint: "Felt before it's understood"},
  {word: "volcanic", hint: "Patient for centuries, then not"},
  {word: "waning", hint: "Bright and then less so"},
  {word: "warpath", hint: "Direction with grievances"},
  {word: "wasteland", hint: "What's left when care runs out"},
  {word: "waterfall", hint: "A river making a decision"},
  {word: "weather", hint: "What the sky is doing to the earth"},
  {word: "wetlands", hint: "Where water and land negotiate"},
  {word: "whirlpool", hint: "Water circling its own conclusion"},
  {word: "wilderness", hint: "Where humans are the guests"},
  {word: "windswept", hint: "Shaped by what passed through"},
  {word: "withered", hint: "Life leaving slowly"},
  {word: "wretched", hint: "Worse than bad, close to hopeless"},
  {word: "yearning", hint: "Wanting something just out of reach"},
  {word: "yielding", hint: "Gives way so others can pass"},
  {word: "abandon", hint: "Left behind on purpose"},
  {word: "absolve", hint: "Guilt quietly lifted away"},
  {word: "acquire", hint: "Made yours without making it"},
  {word: "adrift", hint: "Moving without deciding where"},
  {word: "afterglow", hint: "Light that lingers after the source"},
  {word: "airflow", hint: "Movement you feel but rarely see"},
  {word: "alchemy", hint: "Turning change into something valuable"},
  {word: "amplify", hint: "Making something harder to ignore"},
  {word: "anchored", hint: "Held in place despite intention"},
  {word: "antler", hint: "A crown that grows and leaves"},
  {word: "apricot", hint: "Softness with a hidden centre"},
  {word: "archive", hint: "Where memory is stored on purpose"},
  {word: "armoury", hint: "Prepared for what might come"},
  {word: "arrival", hint: "The end of one kind of movement"},
  {word: "ashfall", hint: "The sky remembering fire"},
  {word: "aspire", hint: "Looking upward without moving yet"},
  {word: "awning", hint: "Shade that isn't part of the sky"},
  {word: "backdrop", hint: "Important without being noticed"},
  {word: "barrage", hint: "Too much coming at once"},
  {word: "barrenly", hint: "Giving nothing despite expectation"},
  {word: "battled", hint: "Effort remembered by damage"},
  {word: "beholden", hint: "Owing something not easily repaid"},
  {word: "beneath", hint: "Hidden under what is seen"},
  {word: "beseech", hint: "Asking as if it matters deeply"},
  {word: "between", hint: "Not belonging to either side"},
  {word: "boulder", hint: "Too large to ignore, too heavy to move"},
  {word: "boundary", hint: "Where something stops being yours"},
  {word: "bracket", hint: "Holds something within limits"},
  {word: "breathe", hint: "What keeps happening without asking"},
  {word: "brittle", hint: "Strong until touched the wrong way"},
  {word: "cascade", hint: "Falling that becomes many falls"},
  {word: "century", hint: "Longer than one life"},
  {word: "channel", hint: "Guides movement without stopping it"},
  {word: "charred", hint: "Marked permanently by heat"},
  {word: "chasing", hint: "Always behind what you want"},
  {word: "chasmic", hint: "Defined by a deep separation"},
  {word: "circling", hint: "Movement without conclusion"},
  {word: "clarity", hint: "When confusion steps aside"},
  {word: "coastal", hint: "Lives where land meets change"},
  {word: "collapse", hint: "Structure giving up entirely"},
  {word: "collect", hint: "Bringing scattered things together"},
  {word: "comfort", hint: "Makes difficulty easier to stay in"},
  {word: "compass", hint: "Knows direction without moving"},
  {word: "conceal", hint: "Hides without removing"},
  {word: "conduit", hint: "Lets something pass through unchanged"},
  {word: "confine", hint: "Limits where something can be"},
  {word: "consume", hint: "Takes until nothing remains"},
  {word: "contour", hint: "The shape without the substance"},
  {word: "converge", hint: "Different paths agreeing"},
  {word: "corridor", hint: "A path that expects you to follow"},
  {word: "counter", hint: "Responds rather than begins"},
  {word: "crevice", hint: "A useful kind of smallness"},
  {word: "crimson", hint: "A colour that insists"},
  {word: "current", hint: "Movement beneath the surface"},
  {word: "custody", hint: "Held, but not owned"},
  {word: "daybreak", hint: "Night deciding to end"},
  {word: "decline", hint: "A downward kind of change"},
  {word: "defiant", hint: "Refuses to agree quietly"},
  {word: "deliver", hint: "Brings something to its end point"},
  {word: "density", hint: "How much is packed into little"},
  {word: "descend", hint: "Gravity doing the work"},
  {word: "despair", hint: "Hope no longer participating"},
  {word: "destiny", hint: "A future that feels decided"},
  {word: "detour", hint: "The long way becoming necessary"},
  {word: "devour", hint: "Consumes without restraint"},
  {word: "distant", hint: "Far in more than distance"},
  {word: "drifting", hint: "Movement without intention"},
  {word: "drought", hint: "Absence that becomes a problem"},
  {word: "echoing", hint: "Sound refusing to leave"},
  {word: "eclipse", hint: "Something hidden by something else"},
  {word: "endure", hint: "Lasts despite difficulty"},
  {word: "engrave", hint: "Makes memory permanent"},
  {word: "entwine", hint: "Separate things refusing to stay separate"},
  {word: "erosion", hint: "Time wearing things down slowly"},
  {word: "essence", hint: "What remains if everything else is removed"},
  {word: "eternal", hint: "Does not recognise endings"},
  {word: "evident", hint: "Impossible not to notice"},
  {word: "exhaust", hint: "Nothing left to give"},
  {word: "faction", hint: "A part that disagrees with the whole"},
  {word: "falter", hint: "Almost stopping, but not quite"},
  {word: "fathoms", hint: "Depth measured in effort"},
  {word: "feather", hint: "Light enough to ignore gravity briefly"},
  {word: "fervent", hint: "Heat without fire"},
  {word: "flicker", hint: "Light unsure of itself"},
  {word: "fracture", hint: "Where something stopped being whole"},
  {word: "fraying", hint: "Coming apart at the edges"},
  {word: "freight", hint: "Weight carried across distance"},
  {word: "furnace", hint: "Heat with purpose"},
  {word: "glacier", hint: "Movement that pretends to be still"},
  {word: "glimmer", hint: "Light that hasn't decided yet"},
  {word: "gravity", hint: "Always pulling its weight"},
  {word: "harbour", hint: "A place where movement rests"},
  {word: "horizon", hint: "Always further than it looks"},
  {word: "humbled", hint: "Brought back to proportion"},
  {word: "icefall", hint: "Frozen motion collapsing"},
  {word: "immerse", hint: "Goes in completely"},
  {word: "inertia", hint: "Prefers things as they are"},
  {word: "journey", hint: "Defined by its duration"},
  {word: "lantern", hint: "Carries a small piece of certainty"},
  {word: "lattice", hint: "Strength through gaps"},
  {word: "lingers", hint: "Refuses to leave on time"},
  {word: "lowland", hint: "Where everything eventually goes"},
  {word: "maelstrom", hint: "Chaos with a centre"},
  {word: "meander", hint: "Takes its time getting there"},
  {word: "meridian", hint: "A line everyone agreed to believe"},
  {word: "midnight", hint: "The deepest point of night"},
  {word: "miracle", hint: "Doesn't explain itself"},
  {word: "monolith", hint: "One piece, many meanings"},
  {word: "murmurs", hint: "Sound that avoids attention"},
  {word: "narrowed", hint: "Reduced to fewer options"},
  {word: "network", hint: "Strength borrowed from others"},
  {word: "nomadic", hint: "Never staying long enough"},
  {word: "notion", hint: "An idea not fully formed"},
  {word: "obelisk", hint: "A monument pointing upward"},
  {word: "obscure", hint: "Exists but avoids being known"},
  {word: "outlast", hint: "Remains when others don't"},
  {word: "overcast", hint: "The sky keeping things muted"},
  {word: "passage", hint: "Connects without belonging"},
  {word: "patience", hint: "Time used deliberately"},
  {word: "pendant", hint: "Carries meaning close"},
  {word: "perilous", hint: "Danger that doesn't announce itself"},
  {word: "persist", hint: "Refuses to stop"},
  {word: "plateau", hint: "Height without progress"},
  {word: "plummet", hint: "Downward with urgency"},
  {word: "precise", hint: "Nothing extra, nothing missing"},
  {word: "quarrel", hint: "Shared disagreement"},
  {word: "radiant", hint: "Light that insists on being seen"},
  {word: "ravaged", hint: "Marked by what happened"},
  {word: "reckless", hint: "Acts before considering"},
  {word: "refugee", hint: "Left home to keep it"},
  {word: "remnant", hint: "What refused to disappear"},
  {word: "resolve", hint: "Deciding not to turn back"},
  {word: "retreat", hint: "Movement away with intention"},
  {word: "reverie", hint: "Thought drifting on purpose"},
  {word: "riftzone", hint: "Where the ground disagrees"},
  {word: "rupture", hint: "Breaking under pressure"},
  {word: "scenery", hint: "Everything you don't touch"},
  {word: "scarred", hint: "Memory written on the surface"},
  {word: "seeking", hint: "Looking without certainty"},
  {word: "serpent", hint: "Movement without limbs"},
  {word: "shadowed", hint: "Partially kept from light"},
  {word: "shatter", hint: "Breaks into too many pieces"},
  {word: "silence", hint: "What fills the absence"},
  {word: "solitary", hint: "Alone by design"},
  {word: "spectrum", hint: "Variation contained in one idea"},
  {word: "spiraling", hint: "Movement toward a centre"},
  {word: "stagnant", hint: "Not moving, not improving"},
  {word: "starlit", hint: "Light from far away"},
  {word: "subtlety", hint: "Easy to miss if you rush"},
  {word: "surging", hint: "Movement with sudden force"},
  {word: "terrain", hint: "What everything stands on"},
  {word: "torrent", hint: "Too much water at once"},
  {word: "traverse", hint: "Crossing with effort"},
  {word: "tremble", hint: "Movement without control"},
  {word: "twilight", hint: "The sky undecided"},
  {word: "unearth", hint: "Brings hidden things back"},
  {word: "unravel", hint: "Order coming undone"},
  {word: "updraft", hint: "Air choosing to rise"},
  {word: "venture", hint: "Going despite uncertainty"},
  {word: "vibrant", hint: "Full of visible energy"},
  {word: "visible", hint: "Impossible to hide"},
  {word: "waiting", hint: "Time spent without moving"},
  {word: "waypoint", hint: "Not the destination, but necessary"},
  {word: "weathered", hint: "Changed by what passed over it"},
  {word: "whisper", hint: "Sound that avoids attention"},
  {word: "withstand", hint: "Remains despite force"},
  {word: "yearning", hint: "Wanting without having"},
  {word: "abiding", hint: "Remains without needing to try"},
  {word: "acutely", hint: "Felt sharper than expected"},
  {word: "adjacent", hint: "Close, but not quite touching"},
  {word: "adverse", hint: "Moving against what you want"},
  {word: "aeration", hint: "Giving something room to breathe"},
  {word: "aflame", hint: "Fully committed to burning"},
  {word: "afterward", hint: "What comes once it's done"},
  {word: "ageless", hint: "Time passed, but left no mark"},
  {word: "airborne", hint: "Freed from the ground"},
  {word: "allegory", hint: "Says one thing, means another"},
  {word: "allotted", hint: "Given with limits attached"},
  {word: "altitude", hint: "Distance measured upward"},
  {word: "amassing", hint: "Gathering more than needed"},
  {word: "ambient", hint: "Present without announcing itself"},
  {word: "amidst", hint: "Surrounded on all sides"},
  {word: "amplified", hint: "Made impossible to ignore"},
  {word: "anchorage", hint: "A place where movement pauses"},
  {word: "anomaly", hint: "Doesn't fit the pattern"},
  {word: "antidote", hint: "Answers something harmful"},
  {word: "apparent", hint: "Seems obvious, for now"},
  {word: "aperture", hint: "An opening with purpose"},
  {word: "arbiter", hint: "Decides when others can't"},
  {word: "arcadia", hint: "An ideal that probably isn't real"},
  {word: "arduous", hint: "Effort that asks for more effort"},
  {word: "armature", hint: "Support that hides inside"},
  {word: "ascended", hint: "Moved upward with finality"},
  {word: "ashore", hint: "Where the water lets go"},
  {word: "assorted", hint: "Together without matching"},
  {word: "attuned", hint: "Understands without explanation"},
  {word: "austere", hint: "Less, by intention"},
  {word: "averted", hint: "Turned away just in time"},
  {word: "backlash", hint: "The response comes later"},
  {word: "balanced", hint: "Nothing outweighs anything else"},
  {word: "bartered", hint: "Value decided without money"},
  {word: "becoming", hint: "Not yet, but getting there"},
  {word: "bedtime", hint: "The day quietly ends"},
  {word: "befallen", hint: "Something happened to you"},
  {word: "belated", hint: "Arrived after it mattered"},
  {word: "bending", hint: "Changed shape without breaking"},
  {word: "benevolence", hint: "Kindness without expectation"},
  {word: "bestowed", hint: "Given with meaning"},
  {word: "betrayed", hint: "Trust turned against you"},
  {word: "bewilder", hint: "Leaves you without direction"},
  {word: "billowing", hint: "Moves like it has breath"},
  {word: "binding", hint: "Holds things where they are"},
  {word: "blending", hint: "Loses edges by joining"},
  {word: "blossom", hint: "Becomes what it was meant to be"},
  {word: "blurring", hint: "Loses clarity gradually"},
  {word: "boiling", hint: "Heat refusing to stay contained"},
  {word: "boundary", hint: "Where something ends"},
  {word: "branching", hint: "One becoming many"},
  {word: "breaking", hint: "No longer whole"},
  {word: "broadening", hint: "Becoming less narrow"},
  {word: "burdened", hint: "Carrying more than wanted"},
  {word: "burnished", hint: "Made brighter through effort"},
  {word: "cascading", hint: "Falling in sequence"},
  {word: "cautious", hint: "Moves only when sure"},
  {word: "centering", hint: "Bringing things back to balance"},
  {word: "churning", hint: "Restless movement inside"},
  {word: "circulate", hint: "Moves but stays within"},
  {word: "clarified", hint: "No longer confusing"},
  {word: "climbing", hint: "Choosing the harder direction"},
  {word: "cohesion", hint: "Stays together under pressure"},
  {word: "colliding", hint: "Two paths meeting suddenly"},
  {word: "combust", hint: "Transforms through heat"},
  {word: "commence", hint: "Begins with intention"},
  {word: "compress", hint: "Made smaller, not lesser"},
  {word: "concealed", hint: "Hidden but still there"},
  {word: "conclude", hint: "Finds its ending"},
  {word: "concrete", hint: "Solid in every sense"},
  {word: "condense", hint: "Becomes more in less space"},
  {word: "conflict", hint: "Two truths refusing each other"},
  {word: "confront", hint: "Faces what was avoided"},
  {word: "conserve", hint: "Uses less to keep more"},
  {word: "constant", hint: "Refuses to change"},
  {word: "constrain", hint: "Limits what could be"},
  {word: "consume", hint: "Takes until gone"},
  {word: "contract", hint: "Becomes smaller"},
  {word: "converge", hint: "Different paths agreeing"},
  {word: "conveyed", hint: "Moved from one to another"},
  {word: "corroded", hint: "Worn down from within"},
  {word: "creating", hint: "Bringing something new"},
  {word: "crescent", hint: "Not quite whole yet"},
  {word: "crippled", hint: "Made less than before"},
  {word: "crossing", hint: "Between two places"},
  {word: "crowding", hint: "Too much in one space"},
  {word: "crushing", hint: "Pressure winning"},
  {word: "cultivate", hint: "Helps something grow"},
  {word: "curling", hint: "Turning inward"},
  {word: "darkened", hint: "Light no longer wins"},
  {word: "dawning", hint: "Understanding begins slowly"},
  {word: "decaying", hint: "Time taking things apart"},
  {word: "deceived", hint: "Believed what wasn't true"},
  {word: "declared", hint: "Said without hiding"},
  {word: "declining", hint: "Moving downward over time"},
  {word: "dedicated", hint: "Given fully to something"},
  {word: "defining", hint: "Gives shape to meaning"},
  {word: "delayed", hint: "Happened later than planned"},
  {word: "delicate", hint: "Easily changed by force"},
  {word: "demanding", hint: "Asks for more than usual"},
  {word: "denoting", hint: "Points directly at meaning"},
  {word: "departed", hint: "Left without returning"},
  {word: "depicting", hint: "Shows without being"},
  {word: "depleting", hint: "Becoming less over time"},
  {word: "descending", hint: "Going with gravity"},
  {word: "deserving", hint: "Earned without asking"},
  {word: "detailing", hint: "Filling in what was missing"},
  {word: "deteriorate", hint: "Gets worse slowly"},
  {word: "developing", hint: "Not finished becoming"},
  {word: "diminish", hint: "Becomes less noticeable"},
  {word: "directing", hint: "Choosing the path forward"},
  {word: "disarray", hint: "Order left the room"},
  {word: "disclose", hint: "Reveals what was hidden"},
  {word: "disperse", hint: "Spreads until it's thin"},
  {word: "dissolve", hint: "Stops being separate"},
  {word: "distance", hint: "Measured in more than space"},
  {word: "distinct", hint: "Clearly not something else"},
  {word: "distorted", hint: "Changed from what it was"},
  {word: "diverging", hint: "Moving away from each other"},
  {word: "dominion", hint: "Control that extends outward"},
  {word: "drifting", hint: "Moves without deciding where"},
  {word: "droplets", hint: "Small pieces of something larger"},
  {word: "dwindling", hint: "Becoming less over time"},
  {word: "earthbound", hint: "Cannot leave what holds it"},
  {word: "elevated", hint: "Raised above what surrounds it"},
  {word: "emerging", hint: "Becoming visible at last"},
  {word: "encounter", hint: "Meeting without planning"},
  {word: "enduring", hint: "Lasts longer than expected"},
  {word: "engulfed", hint: "Surrounded with no escape"},
  {word: "enclosed", hint: "Kept within boundaries"},
  {word: "encompass", hint: "Contains without excluding"},
  {word: "enriched", hint: "Made better by addition"},
  {word: "entangled", hint: "Difficult to separate"},
  {word: "entirety", hint: "Nothing left out"},
  {word: "entrance", hint: "The way in, not the way out"},
  {word: "envision", hint: "Sees before it exists"},
  {word: "ephemeral", hint: "Here briefly, then gone"},
  {word: "equalize", hint: "Removes the difference"},
  {word: "erupting", hint: "Held back until it wasn’t"},
  {word: "escaping", hint: "Leaving what held it"},
  {word: "essaying", hint: "Attempting without certainty"},
  {word: "estranged", hint: "Once close, now not"},
  {word: "evading", hint: "Avoids being caught"},
  {word: "evolving", hint: "Changing without stopping"},
  {word: "exacting", hint: "Demands precision"},
  {word: "exceeding", hint: "More than what was set"},
  {word: "excluding", hint: "Leaves something out"},
  {word: "expanding", hint: "Taking up more space"},
  {word: "expectant", hint: "Waiting for what should come"},
  {word: "expelled", hint: "Forced to leave"},
  {word: "exposing", hint: "Reveals what was hidden"},
  {word: "extended", hint: "Made to last longer"},
  {word: "extracting", hint: "Taking from within"},
  {word: "faltering", hint: "Almost failing"},
  {word: "favorable", hint: "Leans in your direction"},
  {word: "feigning", hint: "Pretends convincingly"},
  {word: "fidelity", hint: "Stays true over time"},
  {word: "filtering", hint: "Lets some through, not all"},
  {word: "finality", hint: "No more after this"},
  {word: "fissuring", hint: "Beginning to split apart"},
  {word: "fluctuate", hint: "Doesn’t stay the same"},
  {word: "focusing", hint: "Brings clarity to one thing"},
  {word: "foreseen", hint: "Knew before it happened"},
  {word: "forever", hint: "Time without end"},
  {word: "forgiving", hint: "Lets go of what was owed"},
  {word: "fragment", hint: "A smaller part of a whole"},
  {word: "freefall", hint: "No control on the way down"},
  {word: "friction", hint: "Resistance that slows things"},
  {word: "frontier", hint: "Where known things stop"},
  {word: "gathered", hint: "Brought together over time"},
  {word: "glancing", hint: "Seen without stopping"},
  {word: "gleaming", hint: "Light reflecting cleanly"},
  {word: "gliding", hint: "Moves without effort"},
  {word: "gradual", hint: "Change that takes its time"},
  {word: "grasping", hint: "Trying to hold onto"},
  {word: "grounded", hint: "Held by reality"},
  {word: "hardship", hint: "Difficulty that lingers"},
  {word: "harshness", hint: "Lacks softness entirely"},
  {word: "hesitate", hint: "Pauses before deciding"},
  {word: "hindered", hint: "Slowed by something else"},
  {word: "hovering", hint: "Neither landing nor leaving"},
  {word: "illuminate", hint: "Makes visible through light"},
  {word: "imbalance", hint: "One side outweighs the other"},
  {word: "immersed", hint: "Fully surrounded"},
  {word: "impending", hint: "About to happen soon"},
  {word: "imposing", hint: "Difficult to ignore"},
  {word: "imprints", hint: "Leaves a lasting mark"},
  {word: "inclined", hint: "Leaning in a direction"},
  {word: "incoming", hint: "On its way here"},
  {word: "increase", hint: "Becomes more than before"},
  {word: "indirect", hint: "Doesn’t take the straight path"},
  {word: "indulged", hint: "Allowed more than needed"},
  {word: "inevitable", hint: "Will happen regardless"},
  {word: "inferred", hint: "Understood without being told"},
  {word: "infinite", hint: "Without measurable end"},
  {word: "influence", hint: "Changes without touching"},
  {word: "informed", hint: "Knows what matters"},
  {word: "ingested", hint: "Taken in completely"},
  {word: "inherent", hint: "Built into its nature"},
  {word: "initial", hint: "The very beginning"},
  {word: "injuring", hint: "Causes harm"},
  {word: "innocent", hint: "Free from blame"},
  {word: "inscribe", hint: "Writes in a lasting way"},
  {word: "insightful", hint: "Sees deeper than most"},
  {word: "inspired", hint: "Moved to create"},
  {word: "intact", hint: "Still whole"},
  {word: "integral", hint: "Necessary to the whole"},
  {word: "intended", hint: "Planned from the start"},
  {word: "intense", hint: "Strong beyond comfort"},
  {word: "interact", hint: "Affecting each other"},
  {word: "interim", hint: "Between two moments"},
  {word: "interval", hint: "Space between events"},
  {word: "intrinsic", hint: "Exists within by default"},
  {word: "invading", hint: "Enters without permission"},
  {word: "inverted", hint: "Turned upside down"},
  {word: "isolated", hint: "Separated from everything else"},
  {word: "junction", hint: "Where paths meet"},
  {word: "justified", hint: "Given a reason to exist"},
  {word: "keystone", hint: "Holds everything together"},
  {word: "languish", hint: "Remains without progress"},
  {word: "layering", hint: "Built one on another"},
  {word: "leverage", hint: "Uses advantage carefully"},
  {word: "lingering", hint: "Stays longer than needed"},
  {word: "loosening", hint: "Becoming less tight"},
  {word: "manifest", hint: "Becomes real and visible"},
  {word: "measured", hint: "Done with careful limits"},
  {word: "melding", hint: "Becomes one from many"},
  {word: "midpoint", hint: "Halfway between ends"},
  {word: "migrating", hint: "Moves with the seasons"},
  {word: "moderate", hint: "Neither extreme nor lacking"},
  {word: "momentum", hint: "Movement that builds itself"},
  {word: "monitored", hint: "Watched continuously"},
  {word: "mounting", hint: "Increasing with pressure"},
  {word: "narrowing", hint: "Becoming more limited"},
  {word: "negating", hint: "Cancels something out"},
  {word: "noticing", hint: "Becomes aware of"},
  {word: "nurtured", hint: "Helped to grow"},
  {word: "observed", hint: "Seen carefully"},
  {word: "obstruct", hint: "Gets in the way"},
  {word: "obtained", hint: "Successfully gained"},
  {word: "offering", hint: "Given without demand"}
];

export const WORDS = [...EMOJI_WORDS, ...DEFINED_WORDS];;
